//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string Hoten { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public Nullable<int> MaPB { get; set; }
    
        public virtual Phongban Phongban { get; set; }
    }
}
